### ISSUE TITLE
I still facing Cross-site request forgery validation failed. The "state" param from the URL and session do not match

### ISSUE THREAD

**Issue by youyi1314** [SammyK/LaravelFacebookSdk#120]
May i know is this sdk fix "Cross-site request forgery validation failed. The "state" param from the URL and session do not match" ?
Because i still facing this problem.
Any one any solution with this?
Thanks

**Comment by imkevinabraham** [comment]
After a lot of time waste the way I fixed it was to use a controller for the login instead of placing the code in routes and then had to put `use \Session;` after the name space and it it started working. Note: Im using laravel 5.1. For 5.2 I just put it in the `Route::group(['middleware' => ['web']], function () {` route and it worked.

**Comment by youyi1314** [comment]
@imkevinabraham Thanks for reply,
I did, but still the same problem.
```
Route::group(['middleware' => ['web']], function () {
    Route::get('login', array('as' => 'login', 'uses' => 'SocialAuthController@login'));
    //Route::get('facebook/callback', array('as' => 'fbcallback','uses' => "SocialAuthController@callback"));
    Route::get('login_callback', array('as' => 'login_callback', 'uses' => "SocialAuthController@callback"));
    //Route::get('facebook/redirect', array('as' => 'fbredirect','uses' => "SocialAuthController@redirect"));
});
```

I using Laravel 5.2 and latest SammyK LaravelFacebookSdk
Thanks

**Comment by zratan** [comment]
insert this code after $helper = $fb->getRedirectLoginHelper();

     ` $_SESSION['FBRLH_state']=$_GET['state'];`
and it wil work or for more detail visit [facebook login apps](http://zrclassroom.com/toturials/creer-une-application-facebook-connect-php-sdk-v5-207)

**Comment by fanals** [comment]
I was getting this error in my log file and finally understood it was happening when someone was denying the facebook connect and then hitting browser back button.

I was missing the getRedirectLoginHelper line. Changed the code from

```
if (!$token) {
  return Redirect::to('/');
}
```

to

```
if (!$token) {
     $helper = $fb->getRedirectLoginHelper();
      if (!$helper->getError())
        abort(403, 'Unauthorized action.');
    return Redirect::to('/');
}
```

I put it here in case someone has the same problem
