### ISSUE TITLE
Cross-site request forgery validation failed. Required param "state" missing.

### ISSUE THREAD

**Issue by sachintaware** [SammyK/LaravelFacebookSdk#66]
I dont know why,but I started getting this issue suddenly.I tried to debug and found in the `FacebookRedirectLoginHelper` the function `validateCsrf()` does not get the savedstate
`$savedState = $this->persistentDataHandler->get('state');`
I am not how to resolve this.I tried printing both the `$state` and `$savedState` and I get $savedState as `null`
Where am I making a mistake with this?
 
    class FacebookController extends Controller {
    public function fbConnect(LaravelFacebookSdk $fb)
    {
        // Obtain an access token.
        try {
            $token = $fb
                ->getRedirectLoginHelper()
                ->getAccessToken();
        } catch (Facebook\Exceptions\FacebookSDKException $e) {
            dd($e->getMessage());
        }
        dd($token);
        // Access token will be null if the user denied the request
        // or if someone just hit this URL outside of the OAuth flow.
        if (! $token) {
            // Get the redirect helper
            $helper = $fb->getRedirectLoginHelper();

            if (! $helper->getError()) {
                abort(403, 'Unauthorized action.');
            }

            // User denied the request
            dd(
                $helper->getError(),
                $helper->getErrorCode(),
                $helper->getErrorReason(),
                $helper->getErrorDescription()
            );
        }
      //Long lived token code after this

**Comment by diridam** [comment]
@sachintaware, are you using mamp ?

**Comment by sachintaware** [comment]
No I am using WAMP. Testing on my local machine,but I also tested it on ubuntu and faced the same.

**Comment by epicsurf** [comment]
@diridam I am getting this error and yes I am using mamp. Is there a fix?

**Comment by diridam** [comment]
@epicsurf, @sachintaware 
I've done a hack for the moment inside facebook's sdk to bypass this. I didn't succeeded to find what's generating this session problem. I've encountered it on MAMP, CentOS. At the begining i thought it was only from MAMP, but looks like there's also present in our prod apps.

I commented out line 249 from FacebookRedirectLoginHelper.php
```
$this->validateCsrf();
```

somehow session vars $state and $savedState from line 268 in the same file, are not being saved.
```
if (!$state || !$savedState) {
            throw new FacebookSDKException('Cross-site request forgery validation failed. Required param "state" missing.');
}
```

i'm not so ok with my time to debug the sessions and get to the roots of the bug. Maybe someone with more time could help us?

**Comment by sachintaware** [comment]
I also tried debugging it.It works fine with the given route examples.But when I add to the custom code it randomly fails.I did the same thing  to skip the process of validation,but somehow not the right way,we all know. I will try and update as I have switched back to this issue
Hope we resolve.

Cheers

**Comment by SammyK** [comment]
I'm thinking this has something to do with how Laravel handles sessions as I've been getting weird inconsistencies with sessions on a similar but unrelated project. I've got it on my TODO list to debug this further. Might be a while before I'm able to dedicate time to it though. :/

**Comment by sachintaware** [comment]
SammyK thank you for attention.Really appreciate​ your efforts and work.This package is really great.
Cheers

**Comment by BogdanHabic** [comment]
Just want to confirm this. I have used this package numerous times, and only today we found out about the bug.
An interesting thing is that the bug (at least in our case) only happens when using Safari. I have no idea why, but Chrome and Firefox work fine. Hope this helps somehow.

**Comment by SammyK** [comment]
Just an update that this is being looked at in the main Facebook PHP SDK repo: facebook-php-sdk-v4#529

**Comment by loranger** [comment]
I've got exactly this bug, using an homebrewed env : Nginx + PHP-FPM.
I also tried with my app inside homestead and the issue remains.

Is there any clue ?

**Comment by BogdanHabic** [comment]
It seems that the issue is fixed now. It will be in the 5.1.2 release.

**Comment by champsupertramp** [comment]
hi @SammyK 

You might need to check the PHP 'register_globals'. 

http://php.net/manual/en/security.globals.php

I had a problem with $_SESSIONS in WordPress core and FacebookSDK 5.0 and it leads me to check the register globals and found out the mystery was there.

**Comment by hfuccillo** [comment]
Hi, I'm still getting this error. I've updated the facebook-php-sdk-v4 to 5.1.2 and this repo to 3.2.0 but the error is still happening.
I waste all day and I'm stuck.
My code:
```
Route::get('facebook', function(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb)
{
    $login_url = $fb->getLoginUrl(['ads_read']);
    echo '<a href="'.$login_url.'">Login</a>';
});

Route::get('/facebook/callback', function(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb) {
    
    try {
        $token = $fb->getAccessTokenFromRedirect();
    } catch (Facebook\Exceptions\FacebookSDKException $e) {
        // Failed to obtain access token
        dd($e->getMessage());
    }

    // $token will be null if the user denied the request
    if (! $token) {
        echo 'User denied the request';
    }
    print_r($token);
});
````

What is wrong with this?
Thanks in advance!

**Comment by itsabadcode** [comment]
@hfuccillo code seems ok.
Probably you have disabled `SessionStart` middleware in `Http/Kernel.php`. It will results in new empty session on callback request.

**Comment by hfuccillo** [comment]
Hi @itsabadcode !
 I haven't disable the SessionStart, I've checked it!

**Comment by francimedia** [comment]
Simply calling e.g. `$app['session']->start();` in your bootstrap file (or similar) fixed the issue for me.

**Comment by Ibrahimna** [comment]
Add 
session_start();

**Comment by w3nh4o** [comment]
put all your route into middleware web

```
Route::group(['middleware' => ['web']], function () {

});
```

**Comment by AwaisRai** [comment]
Adding session_start(); in start of Bootstrap\app.php fixed issue on my side
Thanks @francimedia

**Comment by SammyK** [comment]
I'm going to close this for now since this seems to be an issue with the sessions. If anyone has suggestions on how to fix this in the package, let me know! :)

**Comment by loranger** [comment]
I wonder why you closed it ?
You're right, it seems there is an issue with the sessions, but aren't you supposed to find a fix (or ask for a PR) and leave this bug report open until the issue is resolved and a bugfix commited ?

**Comment by SammyK** [comment]
@loranger I closed it because this seems to be rooted in an issue with the official PHP SDK:  facebook/facebook-php-sdk-v4#529 and not this package. But if anyone finds that it's an issue with this package, I will reopen. :)

**Comment by loranger** [comment]
Ok, 'got it. Thanks for the clarification ;)

**Comment by jonaths** [comment]
Hi... still got the same error. I created a controller and I am having the issue here:

`public function getCallback() {
        // Obtain an access token.
        try {
            $token = $this->fb->getAccessTokenFromRedirect();
            Log::info('FacebookController::getCallBack. token:' . $token);
        } catch (Facebook\Exceptions\FacebookSDKException $e) {
            dd($e->getMessage());
        }
    }`

I checked the threads and I realized that the lines at PersistentDataFactory.php are updated as:

`        if ('session' === $handler) {
            return new FacebookSessionPersistentDataHandler();
        }
        if ('memory' === $handler) {
            return new FacebookMemoryPersistentDataHandler();
        }`

I tried the session start at bootstrap/app.php:

`<?php

session_start();

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| The first thing we will do is create a new Laravel application instance
| which serves as the "glue" for all the components of Laravel, and is
| the IoC container for the system binding all of the various parts.
|
*/

$app = new Illuminate\Foundation\Application(
	realpath(__DIR__.'/../')
);`

However it is not working. Can you help me out @SammyK ?

Thanks!

**Comment by bunlongheng** [comment]
@diridam : I saw you did a hack by comment out this line 

$this->validateCsrf();

Did you ever put it back ? Did you ever find the solution for this ? 

Will this lead to disaster in the future ?

**Comment by sachintaware** [comment]
@bunlongheng Did you try the `session_start` fix by @francimedia ? As far as I remember the same thing worked for me. Also,check if there's any update on the official SDK by Facebook. The new SDK might have a update which would fix it. I have not been working on this for some time and hence wont be able to contribute much though.

@jonaths Try printing the session values their and check if they persist. If they are present you should be through. if not check why what are the values in the session variable.

**Comment by johndoe2509** [comment]
for anyone interested
```
Route::get('facebook', function(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb)
{
    $login_url = $fb->getLoginUrl(['ads_read']);
    return '<a href="'.$login_url.'">Login</a>';
});

```
try change 'echo' to 'return'
i think without 'return' in the function ,session cookie  will not be set , (something to do with request cycle?)

**Comment by v4lerio** [comment]
Make sure the URL from which you want to call the auth method has the same structure of the one provided in the `APP_URL` variable in the `.env` local file.

So if you want to login from `website.com/login`, make sure your `APP_URL` variable in the `.env` local file is `website.com` and NOT `www.website.com`

Of course, the callback URL has to be the same you provide into the SDK config and the one you provide into the FB Login Settings of your App.

After having checked everything else (sessions, methods, Facebook settings, cookies) I solved this issue changing the variable in the `.env` local file from `http://website.dev` to `http://www.website.dev`

I hope this helps!

**Comment by hetsit** [comment]
Hello, i'm got error like, Cross-site request forgery validation failed. Required param "state" missing from persistent data.
so how can i solve this error.

**Comment by cespon** [comment]
> **This happens when the Facebook library cannot match up the state param it receives back from Facebook with the one that it sets, by default, in the session**. Laravel implements its own session storage and the standard Facebook session implementation will likely not work
> 
> To fix it you need to create your own implementation of the `PersistentDataInterface` using your framework's session library and pass this to the `Facebook\Facebook` constructor.

Code: https://developers.facebook.com/docs/php/PersistentDataInterface/5.0.0
Credit: https://stackoverflow.com/a/38116933/3549317
