### ISSUE TITLE
Nothing to publish

### ISSUE THREAD

**Issue by Park66** [SammyK/LaravelFacebookSdk#72]
When I'm trying to First publish the configuration file it says "Nothing to publish". I am using the following commend 
$ php artisan vendor:publish --provider="sammyk/laravel-facebook-sdk" --tag="config"

**Comment by tzfrs** [comment]
I'm having the same problem. Did you fix it? Or what's the reason you closed this?

**Comment by SammyK** [comment]
@tzfrs I didn't close it but @Park66 did. I'm assuming he found the the solution but did not post it here. @Park66 - did you figure out what was going wrong? If so, can you post the solution here?

**Comment by tzfrs** [comment]
Hey, yeah, my comment was directed to him, not you. Sorry if that came wrongly.

However, I'm using Laravel 5.1 Could this be an issue? His comments is 6 days old and Laravel 5.1 was released 6 days ago

**Comment by Park66** [comment]
$ php artisan vendor:publish works for me. But when I'm mentioning the provider then it wasn't working. By the way, I'm using laravel 5.1

**Comment by SammyK** [comment]
> Hey, yeah, my comment was directed to him, not you. Sorry if that came wrongly.

No worries - I misread it. :)

> But when I'm mentioning the provider then it wasn't working. 

Weird. I'll need to do some testing on 5.1 and see if I can reproduce.

**Comment by SammyK** [comment]
This was an error in the docs. The command to publish the config file is:

```bash
$ php artisan vendor:publish --provider="SammyK\LaravelFacebookSdk\LaravelFacebookSdkServiceProvider" --tag="config"
```

I've updated the README as well. :)

**Comment by Park66** [comment]
thanks man.

On Tue, Jun 23, 2015 at 5:24 AM, Sammy Kaye Powers <notifications@github.com
> wrote:

> Closed #72 <https://github.com/SammyK/LaravelFacebookSdk/issues/72>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SammyK/LaravelFacebookSdk/issues/72#event-337272583>.
>



-- 

*MUSA TALUKDAR*

Software Engineer
*Email:* me@musatalukdar.com <anko16@gmail.com> | anko16@gmail.com
<musa.talukdar@gmail.com>
*Phone:* (+88-01717094171)
.............................................................................
Find me on social Media : [image: Facebook]
<http://www.facebook.com/talukdar>[image: Twitter]
<http://twitter.com/anko16>[image: WordPress]
<http://talukdar.wordpress.com/>
Find me on IM: [image: Y! messenger/]ankobd [image: Google Talk/]anko16

**Comment by circuit-monkey** [comment]
I'm still getting this error on laravel 5.1 using the updated publish command

**Comment by UltraWeb** [comment]
Hi @SammyK i'm using laravel 5.2.45.
I'm follow the README and i write this line:
php artisan vendor:publish --provider="SammyK\LaravelFacebookSdk\LaravelFacebookSdkServiceProvider" --tag="config"

but i get the same mistake "Nothing to publish for tag [config]."

How can create the config file manually or this need the other files to publish??
